services:
  postgres-user:
    image: postgres:17
    container_name: postgres-user
    environment:
      POSTGRES_DB: ${POSTGRES_USER_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5433:5432"
    volumes:
      - postgres_user_data:/var/lib/postgresql
    restart: unless-stopped

  postgres-restaurant:
    image: postgres:17
    container_name: postgres-restaurant
    environment:
      POSTGRES_DB: ${POSTGRES_RESTAURANT_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5434:5432"
    volumes:
      - postgres_restaurant_data:/var/lib/postgresql
    restart: unless-stopped

  postgres-order:
    image: postgres:17
    container_name: postgres-order
    environment:
      POSTGRES_DB: ${POSTGRES_ORDER_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5435:5432"
    volumes:
      - postgres_order_data:/var/lib/postgresql
    restart: unless-stopped
volumes:
  postgres_user_data:
  postgres_restaurant_data:
  postgres_order_data:
